### ISSUE TITLE
Memory Overview Is Lacking

### ISSUE THREAD

**Issue by yoosi** [ColinWaddell/CurrantPi#1]
I'd love to see a more detailed breakdown on memory usage. Just showing Free vs Total is not very helpful on a Linux system. What are your thoughts?

**Comment by ColinWaddell** [comment]
Shouldn't be a problem. I was a little lazy with my handling of `/proc/meminfo`

I was considering using bootstrap's stacked progress bars to show a proper breakdown.

![image](https://cloud.githubusercontent.com/assets/1848325/12165638/786d78ca-b517-11e5-9b23-5c5047d319e2.png)

**Comment by ColinWaddell** [comment]
@yoosi I've started modifying the Memory overview to look like this:

![image](https://cloud.githubusercontent.com/assets/1848325/12217276/ab124a16-b6f3-11e5-810b-a9dac2869774.png)

What do you think?

**Comment by yoosi** [comment]
That looks great! Thanks for your work
