### ISSUE TITLE
If the api.php is not on the top level, it will not work correctly

### ISSUE THREAD

**Issue by starbuck93** [ColinWaddell/CurrantPi#39]
Here's what I initially found when I navigated to my clone of the repo at 192.168.1.36/CurrantPi/api.php

`{"error":"Module 'api.php' not available"}`

On line 61 of api.php, I changed the array offset to 3 so it loads the entire api unless you need a module.

`$sourceRequest = $request_uri[3];`

Unless you want to navigate to http://your-ip-address/api.php, you will have to edit that line of code.

**Comment by ColinWaddell** [comment]
This is a big bug, cheers for letting me know. I'll get this sorted in the
next 48 hours.

**Comment by ColinWaddell** [comment]
Hey @starbuck93 That should be the issue sorted (5a8859c5e20dcbb0440efff237644a20a08f3105).

If there's any problems just let me know and I'll reopen the issue.

Cheers again for flagging this!
