### ISSUE TITLE
Storage not loading on Pidora+Apache

### ISSUE THREAD

**Issue by ColinWaddell** [ColinWaddell/CurrantPi#9]
Received the following message via reddit:

> Hey, been trying to get things up and running on my Pi. 
> I'm running Pidora, and Apache, because I find lighttpd
> obnoxious. Here's what I'm getting, any ideas?
> 
> ![image](https://i.imgur.com/uehCjXI.png)

**Comment by z3ntu** [comment]
I am running archlinuxarm with apache and everything works.
http://i.imgur.com/QTRRrN1.png

**Comment by ColinWaddell** [comment]
Nice. I'll try and contact the person who raised this with me to see what
else might be going on.

Cheers for taking the time to check this out on apache for me, I really
appreciate the feedback.

**Comment by z3ntu** [comment]
Well thank YOU for creating this, it looks great and works easy!

**Comment by ColinWaddell** [comment]
Still not been able to recreate. A lot of code has been pushed since then.

Tentatively closing just now - but will reopen if anyone else can recreate.
